### ISSUE TITLE
Can the release zip not contain directories?

### ISSUE THREAD

**Issue by briandipalma** [bootandy/dust#143]
The easiest way to install dust with Ansible is using unarchive and unzipping to a PATH directory.

```
 - name: Install dust
   unarchive:
     src: https://github.com/bootandy/dust/releases/download/v0.5.4/dust-v0.5.4-x86_64-unknown-linux-gnu.tar.gz
     dest: /usr/local/bin
     remote_src: yes
   tags: dust
```

Unfortunately the zip contains a directory instead of the dust executable at the top level of the zip. Could the release zips be flattened in future releases?

**Comment by briandipalma** [comment]
For anyone else who has this issue this is what I did to get just the executable

```
- name: Install dust
  unarchive:
    src: https://github.com/bootandy/dust/releases/download/v0.5.4/dust-v0.5.4-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      # The dust zip contains a directory with the executable and some md files
      # We want to strip the directory and only take the executable
      - "--strip-components=1"
      - "dust-v0.5.4-x86_64-unknown-linux-gnu/dust"
  tags: dust
```
